// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRqfqj6MIKz3OpzU_QrnvsYXbxi1T-n5Q',
    appId: '1:382822226171:web:2b4541899186026eac385e',
    messagingSenderId: '382822226171',
    projectId: 'iot-keamanan-barang',
    authDomain: 'iot-keamanan-barang.firebaseapp.com',
    databaseURL: 'https://iot-keamanan-barang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-keamanan-barang.appspot.com',
    measurementId: 'G-KLPMHHTNLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSLBFbS1xg3o5CbvS8eaUEiFJjJ_oxJVE',
    appId: '1:382822226171:android:469f2b73eae162b6ac385e',
    messagingSenderId: '382822226171',
    projectId: 'iot-keamanan-barang',
    databaseURL: 'https://iot-keamanan-barang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-keamanan-barang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCArow1a71LUS_8t8XPYsHqAML9vwL4Yxw',
    appId: '1:382822226171:ios:93925229854774b6ac385e',
    messagingSenderId: '382822226171',
    projectId: 'iot-keamanan-barang',
    databaseURL: 'https://iot-keamanan-barang-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'iot-keamanan-barang.appspot.com',
    iosClientId: '382822226171-o6ofr4hs4qeu1oeqj02j7e4tq6lmg1ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.iotKeamananBarangApp',
  );
}
